Disable 90% of startup checks
OneSignal/sidekiq pull request #2
Opened 2021-04-22 03:52 UTC by briansfma

ref: https://app.asana.com/0/1198103229139841/1200127065515039

Restarting sidekiq in production currently leads to a huge CPU
spike on redis as hundreds of sidekiq processes simultaneously
spawn and look for jobs to schedule. This is technically all
redundant after the first process, however, it is risky to rely
only on one process (what if the process crashes or the server
goes down).

The suggested temporary patch (implemented in this commit)
randomizes which processes will start enqueuing jobs on startup,
allowing only 10% of calls to proceed. This should reduce the load
load on redis for now for very minimal work, but long-term we
should look at not having to rely on custom forks of sidekiq and
sidekiq-cron to do our scheduling.

This is a WIP PR, currently testing the behavior which is why there
are two extra commits that set FRACTION_TO_RUN to 0 and 1.
These two commits are intended to be removed before merge.

2021-04-22 18:36 UTC, nate-onesignal commented
Hey @briansfma I'm removing myself from this PR for now, feel free to add me when it's ready for review.

2021-04-23 18:02 UTC, nate-onesignal requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/sidekiq/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @briansfma and @niels-s)

___
*[lib/sidekiq/scheduled.rb, line 65 at r1](https://reviewable.io/reviews/onesignal/sidekiq/2#-MYztMtOAh4ZoW5Q8CnU:-MYztMtP8IW2deLqnAUn:b70zzfc) ([raw file](https://github.com/onesignal/sidekiq/blob/524071a6383462956f316eb0618f71fd8c988da5/lib/sidekiq/scheduled.rb#L65)):*
> ```Ruby
> 
>       def start
>         if rand() < FRACTION_TO_RUN
> ```

Why use RNG here instead of host-based disabling like we did for sidekiq-cron?


<!-- Sent from Reviewable.io -->

2021-04-23 18:12 UTC, briansfma reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/sidekiq/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nate-onesignal and @niels-s)

___
*[lib/sidekiq/scheduled.rb, line 65 at r1](https://reviewable.io/reviews/onesignal/sidekiq/2#-MYztMtOAh4ZoW5Q8CnU:-MYztxQ61nMo9gA5WGdw:b-ghxo5v) ([raw file](https://github.com/onesignal/sidekiq/blob/524071a6383462956f316eb0618f71fd8c988da5/lib/sidekiq/scheduled.rb#L65)):*
<details><summary><i>Previously, nate-onesignal (Nate Mara) wrote…</i></summary><blockquote>

Why use RNG here instead of host-based disabling like we did for sidekiq-cron?
</blockquote></details>

Honestly, don't know - the Dropbox Paper seemed to be against leaving only one process to do the startup checks, but wanted to use as few processes as possible. Since there's many processes running on each host, it seemed like host-based disabling would be more like [this host]  * [only the first process] for the selection criteria. That's more annoying to implement than what we did for sidekiq-cron so Brett suggested just using RNG.

With that said... if it's okay to just use host-based disabling exactly like sidekiq-cron, I'd love to do it this way instead. I think that the location of the lever (at the start/thread-spawning point) is correct, I can change it out quickly.


<!-- Sent from Reviewable.io -->

2021-04-23 18:21 UTC, nate-onesignal requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/sidekiq/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @briansfma and @niels-s)

___
*[lib/sidekiq/scheduled.rb, line 65 at r1](https://reviewable.io/reviews/onesignal/sidekiq/2#-MYztMtOAh4ZoW5Q8CnU:-MYzw0gg9C4pHES1PcXW:b-p7v24s) ([raw file](https://github.com/onesignal/sidekiq/blob/524071a6383462956f316eb0618f71fd8c988da5/lib/sidekiq/scheduled.rb#L65)):*
<details><summary><i>Previously, briansfma (Brian Ma) wrote…</i></summary><blockquote>

Honestly, don't know - the Dropbox Paper seemed to be against leaving only one process to do the startup checks, but wanted to use as few processes as possible. Since there's many processes running on each host, it seemed like host-based disabling would be more like [this host]  * [only the first process] for the selection criteria. That's more annoying to implement than what we did for sidekiq-cron so Brett suggested just using RNG.

With that said... if it's okay to just use host-based disabling exactly like sidekiq-cron, I'd love to do it this way instead. I think that the location of the lever (at the start/thread-spawning point) is correct, I can change it out quickly.
</blockquote></details>

I think it's preferrible to use an env var and control that at the host level. Going from ~30 hosts running this to ~3 would be a huge reduction in overhead, even if we don't get all the way there due to multiple processes per host. With env vars, we also have the ability to pair down to single process per host if we want to.


<!-- Sent from Reviewable.io -->

2021-04-23 18:23 UTC, briansfma reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/sidekiq/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nate-onesignal and @niels-s)

___
*[lib/sidekiq/scheduled.rb, line 65 at r1](https://reviewable.io/reviews/onesignal/sidekiq/2#-MYztMtOAh4ZoW5Q8CnU:-MYzxzU876-NZiwtmkHD:b-1sg9bk) ([raw file](https://github.com/onesignal/sidekiq/blob/524071a6383462956f316eb0618f71fd8c988da5/lib/sidekiq/scheduled.rb#L65)):*
<details><summary><i>Previously, nate-onesignal (Nate Mara) wrote…</i></summary><blockquote>

I think it's preferrible to use an env var and control that at the host level. Going from ~30 hosts running this to ~3 would be a huge reduction in overhead, even if we don't get all the way there due to multiple processes per host. With env vars, we also have the ability to pair down to single process per host if we want to.
</blockquote></details>

Sounds good to me - I'll make those changes.


<!-- Sent from Reviewable.io -->

2021-04-23 19:42 UTC, closed without merging